title:              Antoine Dubois
email:              antoine-dubois@hotmail.com
description:        Speaking about energy, climate, education, ...
author:             Antoine Dubois
baseurl:            ""
url:                "https://duboisa1.github.io"

# Social Profiles
twitter_username:   antoinempDubois
github_username:    duboisa1
facebook_username:
instagram_username: antoinempdubois
linkedin_username: duboisantoinemartinpascal

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
